import { basename } from "node:path";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";
import { newEvaluator } from "../index.ts";
import { TextSource } from "../module-source.ts";
import type { PklObject } from "../pkl.ts";
import type { EvaluatorOptions } from "../evaluator-options.ts";

/** A single generated TypeScript file. */
export interface GeneratedFile {
  /** Suggested output filename (e.g. `Sample.pkl.ts`). */
  filename: string;
  /** TypeScript source text. */
  contents: string;
}

/**
 * The Pkl program that reflects over a target module and emits a plain-data
 * schema descriptor. `%TARGET%` is replaced with the target module URI.
 */
const REFLECT_TEMPLATE = `
import "pkl:reflect" as reflect
import "%TARGET%" as target

local mod = reflect.Module(target)

function typeDesc(t) =
  let (cn = t.getClass().simpleName)
    if (cn == "DeclaredType") new Dynamic { kind = "declared"; name = t.referent.reflectee.simpleName; args = t.typeArguments.map((a) -> typeDesc(a)) }
    else if (cn == "NullableType") new Dynamic { kind = "nullable"; of = typeDesc(t.member) }
    else if (cn == "UnionType") new Dynamic { kind = "union"; members = t.members.map((a) -> typeDesc(a)) }
    else if (cn == "StringLiteralType") new Dynamic { kind = "stringLiteral"; value = t.value }
    else if (cn == "NothingType") new Dynamic { kind = "nothing" }
    else if (cn == "UnknownType") new Dynamic { kind = "unknown" }
    else if (cn == "ModuleType") new Dynamic { kind = "module" }
    else new Dynamic { kind = "other"; raw = cn }

function propDesc(p) = new Dynamic { name = p.name; doc = p.docComment; type = typeDesc(p.type) }
function classDesc(c) = new Dynamic { name = c.name; doc = c.docComment; properties = c.properties.values.map((p) -> propDesc(p)) }

schema = new Dynamic {
  moduleClass = classDesc(mod.moduleClass)
  classes = mod.classes.values.map((c) -> classDesc(c))
}
`;

interface TypeDesc extends PklObject {
  kind: string;
  name?: string;
  args?: TypeDesc[];
  of?: TypeDesc;
  members?: TypeDesc[];
  value?: string;
  raw?: string;
}

interface PropDesc extends PklObject {
  name: string;
  doc: string | null;
  type: TypeDesc;
}

interface ClassDesc extends PklObject {
  name: string;
  doc: string | null;
  properties: PropDesc[];
}

/** Runtime types from this package that a generated file may reference. */
const RUNTIME_TYPES = new Set([
  "Duration",
  "DataSize",
  "Pair",
  "IntSeq",
  "Regex",
  "PklObject",
]);

/**
 * Generate TypeScript type definitions for a Pkl module. `modulePath` is a path
 * to a `.pkl` file. Returns the file to write; it does not touch the filesystem.
 */
export async function generateTypes(
  modulePath: string,
  options: { packageName?: string; evaluatorOptions?: EvaluatorOptions } = {},
): Promise<GeneratedFile> {
  const abs = resolve(modulePath);
  const targetUri = pathToFileURL(abs).toString();
  const program = REFLECT_TEMPLATE.replace("%TARGET%", targetUri);

  const evaluator = await newEvaluator(options.evaluatorOptions ?? {});
  let schema: PklObject;
  try {
    schema = await evaluator.evaluateExpression<PklObject>(
      TextSource(program, targetUri.replace(/[^/]+$/, "__pkl_gen__.pkl")),
      "schema",
    );
  } finally {
    evaluator.close();
  }

  const moduleName = pascalCase(basename(abs).replace(/\.pkl$/, ""));
  const contents = render(schema, moduleName, options.packageName ?? "pkl-typescript");
  return { filename: `${basename(abs)}.ts`, contents };
}

function render(schema: PklObject, moduleName: string, packageName: string): string {
  const moduleClass = schema.moduleClass as ClassDesc;
  const classes = (schema.classes as ClassDesc[]) ?? [];

  const usedRuntime = new Set<string>();
  const interfaces: string[] = [];

  // The module itself becomes an interface named after the file.
  interfaces.push(renderInterface(moduleName, moduleClass, usedRuntime));
  for (const c of classes) {
    interfaces.push(renderInterface(c.name, c, usedRuntime));
  }

  const blocks: string[] = ["// Code generated by pkl-gen-typescript. DO NOT EDIT."];
  if (usedRuntime.size > 0) {
    const imports = [...usedRuntime].sort().join(", ");
    blocks.push(`import type { ${imports} } from "${packageName}";`);
  }
  blocks.push(...interfaces);

  return blocks.join("\n\n") + "\n";
}

function renderInterface(
  name: string,
  cls: ClassDesc,
  usedRuntime: Set<string>,
): string {
  const lines: string[] = [];
  if (cls.doc) lines.push(...jsdoc(cls.doc, ""));
  lines.push(`export interface ${name} {`);
  for (const prop of cls.properties ?? []) {
    if (prop.doc) lines.push(...jsdoc(prop.doc, "  "));
    const tsType = renderType(prop.type, usedRuntime);
    lines.push(`  ${quoteKey(prop.name)}: ${tsType};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function renderType(type: TypeDesc, used: Set<string>): string {
  switch (type.kind) {
    case "declared":
      return renderDeclared(type, used);
    case "nullable":
      return `${renderType(type.of!, used)} | null`;
    case "union": {
      const parts = (type.members ?? []).map((m) => renderType(m, used));
      return parts.length ? parts.join(" | ") : "never";
    }
    case "stringLiteral":
      return JSON.stringify(type.value);
    case "nothing":
      return "never";
    case "module":
    case "unknown":
    default:
      return "unknown";
  }
}

function renderDeclared(type: TypeDesc, used: Set<string>): string {
  const name = type.name ?? "unknown";
  const args = type.args ?? [];
  const arg = (i: number) => (args[i] ? renderType(args[i]!, used) : "unknown");

  switch (name) {
    case "String":
    case "Char":
      return "string";
    case "Int":
    case "Float":
    case "Number":
    case "Int8":
    case "Int16":
    case "Int32":
    case "UInt":
    case "UInt8":
    case "UInt16":
    case "UInt32":
      return "number";
    case "Boolean":
      return "boolean";
    case "Null":
      return "null";
    case "Any":
    case "Object":
      return "unknown";
    case "Dynamic":
      used.add("PklObject");
      return "PklObject";
    case "Listing":
    case "List":
    case "Collection":
      return `${wrap(arg(0))}[]`;
    case "Set":
      return `Set<${arg(0)}>`;
    case "Mapping":
    case "Map":
      return `Map<${arg(0)}, ${arg(1)}>`;
    case "Pair":
      used.add("Pair");
      return `Pair<${arg(0)}, ${arg(1)}>`;
    case "Duration":
      used.add("Duration");
      return "Duration";
    case "DataSize":
      used.add("DataSize");
      return "DataSize";
    case "Regex":
      used.add("Regex");
      return "Regex";
    case "IntSeq":
      used.add("IntSeq");
      return "IntSeq";
    default:
      // A user-defined class/type alias in the module: reference by name.
      if (RUNTIME_TYPES.has(name)) used.add(name);
      return name;
  }
}

/** Parenthesize a union so `(a | b)[]` reads correctly. */
function wrap(t: string): string {
  return /[|&]/.test(t) ? `(${t})` : t;
}

function jsdoc(text: string, indent: string): string[] {
  const lines = text.split("\n");
  if (lines.length === 1) return [`${indent}/** ${lines[0]} */`];
  return [
    `${indent}/**`,
    ...lines.map((l) => `${indent} * ${l}`),
    `${indent} */`,
  ];
}

function quoteKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function pascalCase(s: string): string {
  return s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}
